name: .NET Deployment to AWS IIS

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Deploy to IIS
      run: |
        # Copy files to your IIS directory
        robocopy ${{ github.workspace }}/publish \\<172.30.192.6>\D:\Websites\NearMe\UAT /MIR
      env:
        DEPLOY_USER: ${{ secrets.AWS_USERNAME }}
        DEPLOY_PASS: ${{ secrets.AWS_PASSWORD }}
